### ISSUE TITLE
Trying to play anything immediately crashes

### ISSUE THREAD

**Issue by moopet** [tsirysndr/tunein-cli#16]
Running this on WSL with rustc 1.75.0 (82e1608df 2023-12-21) and running `tunein play <any id>` immediately crashes with this:

```
thread '<unnamed>' panicked at src/play.rs:91:22:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/app.rs:185:45:
called `Option::unwrap()` on a `None` value
```

**Comment by moopet** [comment]
Searching seems to work ok (though the results don't always contain the terms searched for so I'm not 100% this is working either). It's just the player that explodes.

**Comment by tsirysndr** [comment]
Thank you, @moopet , for reporting this issue and providing details about the crash you encountered.

I've taken note of the problem you described, and it appears to be addressed in Pull Request #17 . This PR includes fixes to resolve the crash.

I appreciate your patience and encourage you to test the fix provided in PR #17 to confirm that it resolves the issue. If you encounter any further difficulties or have additional feedback, please don't hesitate to let me know. I'm here to help.

**Comment by andykelk** [comment]
I had the same issue. Compiling the latest `master` with #17 included solved the issue.
